Login/LoginService/LoginVue/Models/ErrorViewModel.cs
using System;

namespace LoginVue.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Login/LoginService/LoginVue/Models/Login.cs
using System.ComponentModel.DataAnnotations;

namespace LoginVue.Models
{
    public class Login
    {   
        [Required]
        [MaxLength(254)]
        public string username { get; set; }

        [Required]
        [MaxLength(254)]
        public string email { get; set; }

        [Required]
        [MaxLength(254)]
        public string password { get; set; }

    }

    public class internalMessage
    {
        public int id { get; set; }
        public string msg { get; set; }
    }
}

Login/LoginService/LoginVue/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using LoginVue.Models;
using LoginVue.utilities;

namespace LoginVue.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index()
        {
            if(Request.IsAjaxRequest())
            return PartialView();

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Wallet()
        {
            if(Request.IsAjaxRequest())
            return PartialView();

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Login/LoginService/LoginVue/Controllers/SigninController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LoginVue.Models;
using CoreModule;
using System.Text.Json;
using System.Text.Json.Serialization;
using LoginVue.utilities;
using Microsoft.CodeAnalysis.CSharp.Syntax;


namespace LoginVue.Controllers
{
    [Route("api/[Controller]")]
    [ApiController]
    public class SigninController : Controller
    {
        private readonly TestBE _a;
        public Login _myModel;

        public TestBE.test myState;

        public SigninController()
        {
            TestBE context = new TestBE();
            Login myModel = new Login();
            _a = context;
            _myModel = myModel;
        }

        [HttpGet]
        public IActionResult Index()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PostSignin([FromBody] internalMessage val)
        {
            bool check;
            if (val.id == 1)
            {
                check = await _a.incomming(1, val.id, val.msg);
                if (check)
                {
                    return Ok(200);
                }
            }

            if (val.id == 2)
            {
                check = await _a.incomming(1, val.id, val.msg);
                return Ok(200);
            }
            else
            {
                return BadRequest(400);
            }
        }

    }
}

Login/LoginService/LoginVue/Controllers/SignupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using CoreModule;
using LoginVue.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SignupController;
using SignupController.Models;

namespace LoginVue.Controllers
{
    public class SignupController : Controller
    {
        TestBE be = new TestBE();
        public IActionResult Signup()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<IActionResult> Signup([FromBody] Login val)
        {
            UserDataContext userDatadb = new UserDataContext();
            UserNContext userNamedb = new UserNContext();
            PassContext passworddb = new PassContext();
            
            //At this stage we have no userData besides the ID
            //Creating this object automatically generates an ID
            UserDataDB userData = new UserDataDB();

            //Create new username and password database entries with the same key
            UserNDB userName = new UserNDB(userData.UserId);
            userName.Email = val.email;
            userName.UserName = val.username;
            PassDB password = new PassDB(userData.UserId);
            password.Password = val.password;

            userDatadb.Add(userData);
            userNamedb.Add(userName);
            passworddb.Add(password);

            //update the databases
            try
            {
                userDatadb.SaveChanges();
                userNamedb.SaveChanges();
                passworddb.SaveChanges();
            }
            catch (DbUpdateException)
            {
                return StatusCode(StatusCodes.Status500InternalServerError);
            }

            return Ok(200);

            //string newUser = JsonSerializer.Serialize(val);
            //bool complete = await be.incomming(1, 3, newUser);
            //bool complete = true;
            //if (complete)
            //{
            //    return Ok(200);
            //}
            //return BadRequest(400);
        }
    }
}

Login/LoginService/LoginVue/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">This is a test</h1>
</div>

Login/LoginService/LoginVue/Views/Home/Signup.cshtml
@{
    ViewData["Title"] = "Signup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Signup</h1>

Login/LoginService/LoginVue/Views/Home/Wallet.cshtml
@{
    ViewData["Title"] = "Wallet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Wallet</h1>

Login/LoginService/LoginVue/Views/Shared/_Layout.cshtml
@using Microsoft.CodeAnalysis
@using Microsoft.CodeAnalysis.CSharp.Syntax
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Login service</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/normalize.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body onload="checkUser()">
    <div id="wrapper">
        <header>
            <h1>

                <label height="250" width="619">Orctioneer</label>
            </h1>
        </header>
        <meta name="viewport" content="width=device-width">
        <link rel="stylesheet" href="https://cdn.lineicons.com/1.0.1/LineIcons.min.css">

        <div class="navbar" id="Nav" onload="checkUser()">
            <a asp-controller="Home" asp-action="Index">Home</a>
            <a href="#">Coolstuff</a>
            <div class="dropdown">

                <button class="dropbtn">
                    User
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-content">
                    <a v-if="!isUser" asp-controller="Signin" asp-action="index" class="menu doAjax">Signin</a>
                    <a v-if="!isUser" asp-controller="Signup" asp-action="Signup" class="menu doAjax">Signup</a>
                    <a v-if="isUser" asp-controller="Home" asp-action="Wallet" class="menu doAjax">Wallet</a>
                    <a v-if="isUser" href="#" class="menu doAjax">Userinfo</a>
                    <a v-if="isUser" href="#" class="menu doAjax">Signout</a>
                    <Signin class="isActive"></Signin>
                </div>
            </div>
        </div>

        <div>
            <main id="content">
                @RenderBody()
            </main>

            <footer>
            </footer>
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="https://unpkg.com/vue"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>
            <script src="https://unpkg.com/vue@2.6.10/dist/vue.min.js"></script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)
</body>
</html>

Login/LoginService/LoginVue/Views/Signin/Create.cshtml
@model LoginVue.Models.Login
@{
    ViewData["Title"] = "doLogin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

Login/LoginService/LoginVue/Views/Signin/Index.cshtml
@model LoginVue.Models.Login

@{
    ViewData["Title"] = "Signin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="vueSignin">
    <p><center>{{introText}}</center></p>
    <br/>
    <center>
        <div class="modal-open">
            <div>
                <form>
                    <div class="form-group">
                        <label/>
                        <span class="text-danger">
                            <font color="red" size="1">
                                {{UsernameValidationMsg}}
                            </font>
                        </span><br/>
                        <label for="username">Username: </label>
                        <input type="text"
                               v-model="Username"
                               placeholder="Please enter username">*
                    </div>
                    <div class="form-group">
                        <label/>
                        <span class="text-danger">
                            <font color="red" size="1">
                                {{PasswordValidationMsg}}
                            </font>
                        </span><br/>
                        <label for="password" style="padding: 3px">Password:</label>
                        <input type="Password"
                               v-model="Password"
                               placeholder="Please enter password">*
                    </div><br/>
                    <div class="form-group">
                        <center>
                            <button type="button" class="button"
                                    v-on:click="sendApplication"
                                    :disabled="sendDisabled">
                                Signin
                            </button>&nbsp;&nbsp;
                            <button type="button" class="button"
                                    v-on:click="sendPageChange">
                                Signup
                            </button>&nbsp;&nbsp;
                        </center>
                    </div>
                </form>
            </div>
        </div>
    </center></div>

@section Scripts
{
    <script src="~/js/Signin-vue.js" asp-append-version="true"></script>
}

Login/LoginService/LoginVue/Views/Signup/Signup.cshtml
@model LoginVue.Models.Login

@{
    ViewData["Title"] = "Signup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="vueSignin">
    <p><center>{{introText}}</center></p>

    <center>
        <div>
            <div>
                <form>
                    <div class="form-group">
                        <label for="username">Username: </label>
                        <input type="text"
                               v-model="Username"
                               placeholder="Please enter username">*
                        <span class="text-danger">{{UsernameValidationMsg}}</span>
                    </div>
                    <div class="form-group">
                        <label for="email" style="padding: 19px">Email:</label>
                        <input type="text"
                               v-model="Email"
                               placeholder="Please enter email">*
                        <span class="text-danger">{{EmailValidationMsg}}</span>
                    </div>
                    <div class="form-group">
                        <label for="password" style="padding: 3px">Password:</label>
                        <input type="text"
                               v-model="Password"
                               placeholder="Please enter password">*
                        <span class="text-danger">{{PasswordValidationMsg}}</span>
                    </div>
                    <div class="form-group">
                        <center>
                            <button type="button" class="button"
                                    v-on:click="sendApplication"
                                    :disabled="sendDisabled">
                                Signup
                            </button>&nbsp;&nbsp;
                            <button type="button" class="button"
                                    v-on:click="annuller">Annuller</button>
                        </center>
                    </div>
                </form>
            </div>
        </div>
    </center>
</div>

@section Scripts
{
    <script src="~/js/Signup-vue.js" asp-append-version="true"></script>
}